package service

import (
	"bytes"
	"encoding/base64"
	"fmt"
	"strings"
	"time"
)

type SampleReport struct {
	FileName  string `json:"fileName"`
	Title     string `json:"title"`
	PDFBase64 string `json:"pdfBase64"`
	Size      int    `json:"size"`
}

// GenerateSampleReport produces a small, dependency-free PDF in Go. The report
// intentionally uses the built-in Helvetica font so the sidecar stays a single
// binary on every supported OS.
func GenerateSampleReport(now time.Time) SampleReport {
	title := "Tauri Desktop Sample Report"
	lines := []string{
		"Generated by the Go sidecar",
		"Generated at: " + now.UTC().Format(time.RFC3339),
		"",
		"Item                         Quantity        Status",
		"CSV import                         128        Complete",
		"JSON validation                     42        Complete",
		"Background jobs                      3        Ready",
	}
	pdf := buildSimplePDF(title, lines)
	return SampleReport{
		FileName:  "tauri-sample-report.pdf",
		Title:     title,
		PDFBase64: base64.StdEncoding.EncodeToString(pdf),
		Size:      len(pdf),
	}
}

func buildSimplePDF(title string, lines []string) []byte {
	var stream strings.Builder
	stream.WriteString("BT\n/F1 20 Tf\n50 790 Td\n(")
	stream.WriteString(escapePDFText(title))
	stream.WriteString(") Tj\n/F1 11 Tf\n0 -34 Td\n")
	for _, line := range lines {
		stream.WriteString("(")
		stream.WriteString(escapePDFText(line))
		stream.WriteString(") Tj\n0 -20 Td\n")
	}
	stream.WriteString("ET\n")
	content := stream.String()

	objects := []string{
		"<< /Type /Catalog /Pages 2 0 R >>",
		"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
		fmt.Sprintf("<< /Length %d >>\nstream\n%sendstream", len(content), content),
	}

	var pdf bytes.Buffer
	pdf.WriteString("%PDF-1.4\n%\xE2\xE3\xCF\xD3\n")
	offsets := make([]int, len(objects)+1)
	for i, object := range objects {
		offsets[i+1] = pdf.Len()
		fmt.Fprintf(&pdf, "%d 0 obj\n%s\nendobj\n", i+1, object)
	}
	xref := pdf.Len()
	fmt.Fprintf(&pdf, "xref\n0 %d\n0000000000 65535 f \n", len(objects)+1)
	for i := 1; i <= len(objects); i++ {
		fmt.Fprintf(&pdf, "%010d 00000 n \n", offsets[i])
	}
	fmt.Fprintf(&pdf, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objects)+1, xref)
	return pdf.Bytes()
}

func escapePDFText(value string) string {
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "(", "\\(")
	return strings.ReplaceAll(value, ")", "\\)")
}
